/*
Student Name:Saugat karki
Subject     :Programming Fundamentals
Roll        :
Program     :Write a program to print surface and volume of sphere
LAB NO      :01
Date        :18 september,2016
*/
#include<stdio.h>
#include<conio.h>
#include<math.h>

    void main(){
    double a,square;
    clrscr();
    printf("enter the number \n");
    scanf("%lf",&a);
    square=sqrt(a);
    printf("the square root is  %lf \n",square);

    getch();
    }


